name: Run Shell Script with Args  

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run script
      env:
        SCRIPT_ARGS: "Hello world"
      run: |
        pwd
        ls
        chmod +x ./script.sh
        ./script.sh $SCRIPT_ARGS

