name: Run Shell Script with Args  

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run script
      env:
        SCRIPT_ARGS: "Hello world"
        DRY_RUN: "true"
        STALE: "3 months ago"
      run: |
        pwd
        ls
        echo $SCRIPT_ARGS
        echo $DRY_RUN
        echo $STALE

        # chmod +x .github/script/script.sh
        # .github/script/script.sh $SCRIPT_ARGS

